
# OS as ubuntu for face dectection to run
FROM ubuntu

RUN apt update

ENV DEBIAN_FRONTEND=noninteractive

RUN apt install -y python-pip python-opencv vim-tiny mosquitto-clients libopencv-dev

RUN pip install paho-mqtt numpy

WORKDIR /
COPY facedetector.py .

# Run the face detector when the container starts
CMD python facedetector.py


